### ISSUE TITLE
Create HMI mockup

### ISSUE THREAD

**Issue by leandergmeiner** [DHBW-SE-2023/YAAC#29]
Create an HMI mockup in accordance with the requirements.

**Comment by EvaMatz** [comment]
Created first HMI mockup in figma.
Current design can be found in "Course View"
https://www.figma.com/file/LWwEozuodQ2Lx7wjJokTf3/HomeviewEtc?type=design&node-id=0-1&mode=design&t=c5FE5NmS8Z0ZinCN-0 


different question came up:
- both long + short name necessary?
- only absent members shown?
- show only current stats of the day (if no stat available: there will NOT be shown the latest stats for better clarity)
- button to export lists: Should it export the full course list? Or only present/absent students? (Mrs. Schmidt needs one of them only)
- export all lists: "one button to rule them all"? default action, otherwise dropdown menu with various options - last chosen option will be saved as new default action
- what happens with missing courses? (courses that are in their practical phase at their company) - is there an automatic function that hides the affected courses (defined by date)?
- what's the intended format of the application? (web app for PC? app for mobile phone?)
- which features are missing? -> is a side menu necessary?

**Comment by EvaMatz** [comment]
still missing: design guidelines in wiki -> needs good and complete mockup first

**Comment by MaxAlberti** [comment]
Really nice interactive Figma example: https://www.figma.com/proto/iWNlSzDKpTucBNzQymGzyY/Bottles-Next?type=design&node-id=29-1150&t=Ge4CUBp7vcWkoy3l-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=29%3A1150

**Comment by MaxAlberti** [comment]
https://www.ravensburg.dhbw.de/fileadmin/user_upload/Dokumente/Broschueren_Handbuch_Betriebe/DHBW_Imageflyer_Deutsch.pdf

Für Farben etc

**Comment by danielSiegt08** [comment]
HMI Mockup Decision: 
After careful consideration, we'll take the following HIM Mockup as our target HMI Layout:
https://www.figma.com/file/LafaEbsEgrPlpfGFD248Ht/Eva?type=design&node-id=0-1&mode=design&t=8FzSwLmf3dPoZulu-0
Eva will further refine and improve this layout so that we have a well-defined plan, when designing the HMI.

**Comment by EvaMatz** [comment]
Forgot to move this in done.
HMI Mockup is finished, can be viewed with the following link:
https://www.figma.com/file/LafaEbsEgrPlpfGFD248Ht/Eva?type=design&node-id=0-1&mode=design&t=WLknTuXN0PHTvYjs-0
Contains of 5 main views (Overview, Course, Student, Verification, Settings)

**Comment by MaxAlberti** [comment]
Last update 3w ago, closing.

**Comment by EvaMatz** [comment]
While implementing the UI in fyne, it got clear that fyne enforces their style of cornered buttons. Therefore, the original idea of buttons with rounded corners was discarded. 
Thus, the hmi mockup has to be refactored.
