### ISSUE TITLE
Refactor: Consider if type mvvm interface can be moved to shared

### ISSUE THREAD

**Issue by MaxAlberti** [DHBW-SE-2023/YAAC#83]

**Comment by leandergmeiner** [comment]
Isn't the MVVM interface already mostly in shared? It would only make sense to also move the rest of it, if possible.
If I remember correctly for example, Imgproc can't import shared, because elsewise an import cycle would occur. At the moment that is also no problem though, as Imgproc doesn't rely on any of the functinoalities provided by shared.

**Comment by MaxAlberti** [comment]
Closed
